name: CI

on: [push, pull_request]

jobs:
  build:
    name: Generate build and check code formatting

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run format:check
      - run: npm run build
